replicaCount: 1

image:
  repository: 945219712485.dkr.ecr.ap-south-1.amazonaws.com/my_pvt_repo
  tag: "latest"
containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  containerPort: 80
  nodePort: 30008
  
